In [36]:
%reload_ext autoreload
%autoreload 2

In [37]:
from mesh_utils import UniformQuadMesh2D
from feinn_solver import feinn

import numpy as np
import matplotlib.pyplot as plt

In [38]:
lx = 2
ly = 1
nx = 2
ny = 2
element_type = 'Q4'

cantilever_mesh = UniformQuadMesh2D(lx, ly, nx, ny, element_type=element_type)
cantilever_mesh.compute()

In [39]:
cantilever = feinn(cantilever_mesh)

In [41]:
print(cantilever_mesh.elements)

[[5 4 1 2]
 [6 5 2 3]
 [8 7 4 5]
 [9 8 5 6]]
